dist: trusty
sudo: required
language: python
python:
  - "3.6"
addons:
    apt:
      update: true
cache:
  - pip
install:
  - ./build/install-libspatialite.sh
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - pytest --cov=generator