dist: trusty
sudo: false
language: python
addons:
  apt:
    packages:
      - libspatialite3
python:
  - "3.6"
cache:
  - pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - pytest --cov=generator