version: '3.1'

services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile.db
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "oevgk18"
  generator:
    build: 
      context: .
      dockerfile: Dockerfile.python
    environment:
      DB_HOST: "postgres"
      DB_USER: "test"
      DB_PASSWORD: "test"
    depends_on: [db]