FROM python:3

WORKDIR .

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY ./generator ./generator
COPY ./tool ./tool

CMD ["./tool/wait-for-it.sh", "db:5432", "--", "python", "./generator/__main__.py" ]