version: '3.1'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile.db
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: "oevgk18user"
      POSTGRES_PASSWORD: "xkGVsHsTHnkW9wpD"
      PGPASSWORD: "xkGVsHsTHnkW9wpD" # must be the same as POSTGRES_PASSWORD
      POSTGRES_DB: "oevgk18"
    volumes:
      - ./db/terrain-data:/terrain-data
      - sql-import:/sql-import
  tooling:
    build:
      context: ./tooling
      dockerfile: Dockerfile.tooling
    volumes:
      - ./tooling/osm-data:/osm-data
      - sql-import:/sql-import
    depends_on: [db]

  generator:
    build:
      context: ../
    volumes:
      - ./generator:/generator
    depends_on: [db]

volumes:
  sql-import:
