FROM starefossen/pgrouting

RUN /bin/bash -c 'mv /docker-entrypoint-initdb.d/postgis.sh /docker-entrypoint-initdb.d/00_postgis.sh'
RUN /bin/bash -c 'rm /docker-entrypoint-initdb.d/routing.sh'

COPY ./schema/* /docker-entrypoint-initdb.d/

COPY ./scripts /scripts

ENV PATH="/scripts:${PATH}"
